# Generated by Django 4.1.1 on 2022-10-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_exchange', '0002_rename_seller_id_bookforsale_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookforsale',
            old_name='user_id',
            new_name='seller_id',
        ),
    ]
