# Generated by Django 4.1.1 on 2022-10-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_exchange', '0003_rename_user_id_bookforsale_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookforsale',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='pinnedbook',
            old_name='book_listing_id',
            new_name='book_listing',
        ),
        migrations.RenameField(
            model_name='pinnedbook',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='book_listing_id',
            new_name='book_listing',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='buyer_id',
            new_name='buyer',
        ),
    ]
