# Generated by Django 4.1.1 on 2022-11-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_exchange', '0004_rename_seller_id_bookforsale_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsale',
            name='cover',
            field=models.ImageField(default='book_exchange/media/default.jpg', upload_to='static/book_exchange/media/'),
        ),
    ]
