# Generated by Django 4.1.1 on 2022-11-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_exchange', '0004_rename_seller_id_bookforsale_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='Cover'),
        ),
    ]
