# Generated by Django 4.1.1 on 2022-11-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_exchange', '0006_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='media/default.jpg', upload_to=''),
        ),
    ]
