# Generated by Django 4.1.1 on 2022-11-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_exchange', '0009_alter_bookforsale_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_condition',
            field=models.CharField(default='Good', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.TextField(default='Default comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='book_exchange/media/covers/default.jpg', upload_to='book_exchange/media/covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='book_exchange.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pinnedbook',
            name='book_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book_exchange.book'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_exchange.book'),
        ),
        migrations.DeleteModel(
            name='BookForSale',
        ),
    ]
