# Generated by Django 4.1.1 on 2022-11-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_exchange', '0011_book_id_alter_book_isbn_alter_book_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='media/covers/default.jpg', upload_to='media/covers/'),
        ),
    ]
